name: Test build and eslint

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test-build-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        run: yarn
      - name: Check server style
        run: yarn workspace server lint
      - name: Check client style
        run: yarn workspace client lint
      - name: Server Build
        run: yarn workspace server build
      - name: Client Build
        run: yarn workspace client build
