name: Server Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy_to_render:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID_SERVER }}?key=${{ secrets.RENDER_API_KEY_SERVER }}
